### PR TITLE
adjusted upper limit

### PR DESCRIPTION
**Pull request by prolixalias**

### CODE REVIEW

**Comment by prolixalias** [comment]
@chelnak - do you know what I can do to workaround that CI failure by chance? it's pretty odd... Happy to address it myself if I'm able.

**Comment by prolixalias** [comment]
nevermind,  wrong PR for above message - I can address those linting problems ASAP

**Comment by chelnak** [comment]
@prolixalias I'll ask internally about this one too. It's not clear who owns it currently.

**Comment by prolixalias** [comment]
> @prolixalias I'll ask internally about this one too. It's not clear who owns it currently.

Hey there @chelnak! @binford2k suggested I could `pdk update` to get tests passing again. I pushed it up moments ago but the check didn't fire. Am I doing it wrong?   LOL

Also, I'd like to get this one moving forward still... The `stdlib` dep is making ra10ke puke.

**Comment by davidsandilands** [comment]
The changes look good on a visual review, I am unable to get the rspec tests working on the validation tests on a modern supported version of PDK but I think thats beyond the scope of the work here so I will approve

**Review by davidsandilands — APPROVED** [review]
The changes look good on a visual review, I am unable to get the rspec tests working on the validation tests on a modern supported version of PDK but I think thats beyond the scope of the work here so I will approve

**Pull request merged**
